# Centralna konfiguracja funkcji KuroganeOS Foundation.
# Format jest celowo prosty i deterministyczny: CONFIG_NAME=y|n.

CONFIG_CONSOLE=y
CONFIG_GUI=y
CONFIG_PCI=y
CONFIG_AHCI=y
CONFIG_VIRTIO=n
CONFIG_USB=y
CONFIG_XHCI=y
CONFIG_NETWORK=y
CONFIG_POSIX=n
CONFIG_ACPI=y
CONFIG_APIC=y
