#pragma once

#define KUROGANE_VERSION_MAJOR 3
#define KUROGANE_VERSION_MINOR 0
#define KUROGANE_VERSION_PATCH 0
#define KUROGANE_VERSION_STRING "3.0.0"
#define KUROGANE_PRODUCT_STRING "KuroganeOS " KUROGANE_VERSION_STRING
#define KUROGANE_VERSION_WIDE L"3.0.0"
