#pragma once

#define KUROGANE_VERSION_MAJOR 7
#define KUROGANE_VERSION_MINOR 0
#define KUROGANE_VERSION_PATCH 0
#define KUROGANE_VERSION_STRING "7.0.0-dev"
#define KUROGANE_RELEASE_CHANNEL "IRON SHIELD DEV"
#define KUROGANE_PRODUCT_STRING "KuroganeOS " KUROGANE_VERSION_STRING
#define KUROGANE_VERSION_WIDE L"7.0.0-dev"
