#pragma once

#define KUROGANE_VERSION_MAJOR 2
#define KUROGANE_VERSION_MINOR 4
#define KUROGANE_VERSION_PATCH 1
#define KUROGANE_VERSION_STRING "2.4.1"
#define KUROGANE_PRODUCT_STRING "KuroganeOS " KUROGANE_VERSION_STRING
#define KUROGANE_VERSION_WIDE L"2.4.1"
